AWSTemplateFormatVersion: "2010-09-09"
Description: A template for Storage

Parameters:
  S3BucketName:
    Type : 'AWS::SSM::Parameter::Value<String>'
    Default: '/std21045/s3/bucket-name'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref S3BucketName
  SSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Type: String
      Name: s3_bucket_arn
      Value: !GetAtt Bucket.Arn
    DependsOn:
      - MyS3Bucket